mainStore: https://ea-simulator.tebex.io/
sendChat: https://ea-simulator.tebex.io/package/5555043
viewChat: https://ea-simulator.tebex.io/package/5555047
breakBlock: https://ea-simulator.tebex.io/package/5555051
placeBlock: https://ea-simulator.tebex.io/package/5555053
move: https://ea-simulator.tebex.io/package/5555054
see: https://ea-simulator.tebex.io/package/5555055
attack: https://ea-simulator.tebex.io/package/5555062
craft: https://ea-simulator.tebex.io/package/5555070
inventory: https://ea-simulator.tebex.io/package/5555074
jump: https://ea-simulator.tebex.io/package/5555094
crouch: https://ea-simulator.tebex.io/package/5555095
health: https://ea-simulator.tebex.io/package/5555104
sprint: https://ea-simulator.tebex.io/package/5555110
regen: https://ea-simulator.tebex.io/package/5555111
eat: https://ea-simulator.tebex.io/package/5555113
itemhold: https://ea-simulator.tebex.io/package/5555125
command: https://ea-simulator.tebex.io/package/5555126
pickup: https://ea-simulator.tebex.io/package/5555136
drop: https://ea-simulator.tebex.io/package/5555138